name: Build and Create DFU

on:
  workflow_dispatch:  # 👈 Manual trigger enabled

  push:
    tags:
      - '*'  # Only run on tags
    branches-ignore:
      - '**'

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: '!contains(github.event.head_commit.message, ''skip ci'') && !contains(github.event.head_commit.message, ''skip release'')'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.2'

      - name: Install nrfutil 6.1.7
        run: |
          python -m pip install --upgrade pip
          pip install nrfutil==6.1.7

      - name: Download nRF5 SDK
        run: |
          wget https://www.nordicsemi.com/-/media/Software-and-other-downloads/SDKs/nRF5/Binaries/nRF5_SDK_17.1.0_ddde560.zip
          unzip nRF5_SDK_17.1.0_ddde560.zip -d /opt/
          rm nRF5_SDK_17.1.0_ddde560.zip

      - name: Set up environment variables
        run: |
          echo "NRF5_SDK_ROOT=/opt/nRF5_SDK_17.1.0_ddde560" >> $GITHUB_ENV
          echo "GNU_INSTALL_ROOT=/opt/gcc-arm-none-eabi-10.3-2021.10/bin/" >> $GITHUB_ENV
          echo "GNU_VERSION=10.3.1" >> $GITHUB_ENV
          echo "GNU_PREFIX=arm-none-eabi" >> $GITHUB_ENV

      - name: Download ARM GCC
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          tar -xf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 -C /opt/
          rm gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2

      - name: Patch SoftDevice headers
        run: |
          mkdir -p /opt/nRF5_SDK_17.1.0_ddde560/components/softdevice/s340/headers/
          cp -r pca10056/s340/include/* /opt/nRF5_SDK_17.1.0_ddde560/components/softdevice/s340/headers/

      - name: Inject ANT license key
        run: |
          sed -i 's|#define ANT_LICENSE_KEY .*|#define ANT_LICENSE_KEY "'"${{ secrets.ANT_LICENSE_KEY }}"'"|' \
          /opt/nRF5_SDK_17.1.0_ddde560/components/softdevice/s340/headers/nrf_sdm.h

      - name: Build bootloader
        run: |
          cd bootloader/bootloader_s340/armgcc
          make -j4 DEBUG=0 OPT=-O3

      - name: Build application
        run: |
          cd pca10056/s340/armgcc
          make -j4 DEBUG=0 OPT=-O3

      - name: Generate DFU settings
        run: |
          cd pca10056/s340/armgcc
          nrfutil settings generate --family NRF52840 \
            --application _build/nrf52840_xxaa.hex \
            --application-version 1 \
            --bootloader-version 1 \
            --bl-settings-version 2 \
            --app-boot-validation NO_VALIDATION \
            dfu_settings.hex

      - name: Merge firmware hex
        run: |
          cd pca10056/s340/armgcc
          mergehex --merge \
            ../../../../components/softdevice/s340/hex/ANT_s340_nrf52_7.0.1.hex \
            ../../../bootloader/bootloader_s340/armgcc/_build/satsbike_bootloader_s340.hex \
            _build/nrf52840_xxaa.hex \
            dfu_settings.hex \
            --output merged_firmware.hex

      - name: Create DFU package
        run: |
          nrfutil pkg generate --hw-version 52 --sd-req 0x00 \
            --application pca10056/s340/armgcc/_build/nrf52840_xxaa.hex \
            --application-version 1 \
            --softdevice pca10056/s340/hex/ANT_s340_nrf52_7.0.1.hex \
            satsbike_dfu.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: satsbike-firmware
          path: |
            pca10056/s340/armgcc/_build/nrf52840_xxaa.hex
            pca10056/s340/armgcc/_build/nrf52840_xxaa.bin
            pca10056/s340/armgcc/merged_firmware.hex
            satsbike_dfu.zip
          retention-days: 7

      - name: Show firmware size
        run: |
          echo "🚀 Firmware size:"
          stat --printf="%n: %s bytes\n" satsbike_dfu.zip || echo "Not found"
          stat --printf="%n: %s bytes\n" pca10056/s340/armgcc/merged_firmware.hex || echo "Not found"

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pca10056/s340/armgcc/merged_firmware.hex
            satsbike_dfu.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
