name: Build and Create DFU

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches-ignore:
      - '**'
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: '!contains(github.event.head_commit.message, ''skip ci'') && !contains(github.event.head_commit.message, ''skip release'')'
    strategy:
      matrix:
        board: [promicro, pca10056, xiaoble]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Derive version from Git
        id: version
        run: |
          # Determine if this is a tag-based or manual build
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/tags/"* ]]; then
            # This is a tag-based build
            TAG=$(git describe --tags --abbrev=0)
            SHA=$(git rev-parse --short HEAD)
            VERSION="${TAG#v}-${SHA}"
          else
            # This is a manual build or PR
            TAG=$(git describe --tags --abbrev=0)
            SHA=$(git rev-parse --short HEAD)
            VERSION="${TAG#v}-SNAPSHOT-${SHA}"
          fi
          
          echo "Derived version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install nrfutil 6.1.7
        run: |
          python -m pip install --upgrade pip
          pip install nrfutil==6.1.7

      - name: Download nRF5 SDK
        run: |
          wget https://www.nordicsemi.com/-/media/Software-and-other-downloads/SDKs/nRF5/Binaries/nRF5_SDK_17.1.0_ddde560.zip
          unzip nRF5_SDK_17.1.0_ddde560.zip -d /opt/
          rm nRF5_SDK_17.1.0_ddde560.zip

      - name: Install mergehex from Nordic CLI tools
        run: |
          wget https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/desktop-software/nrf-command-line-tools/sw/versions-10-x-x/10-24-2/nrf-command-line-tools-10.24.2_linux-amd64.tar.gz
          tar -xzf nrf-command-line-tools-10.24.2_linux-amd64.tar.gz
          sudo cp nrf-command-line-tools/bin/mergehex /usr/local/bin/
          sudo chmod +x /usr/local/bin/mergehex

      - name: Set up environment variables
        run: |
          echo "NRF5_SDK_ROOT=/opt/nRF5_SDK_17.1.0_ddde560" >> $GITHUB_ENV
          echo "GNU_INSTALL_ROOT=/opt/gcc-arm-none-eabi-10.3-2021.10/bin/" >> $GITHUB_ENV
          echo "GNU_VERSION=10.3.1" >> $GITHUB_ENV
          echo "GNU_PREFIX=arm-none-eabi" >> $GITHUB_ENV

      - name: Download ARM GCC
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          tar -xf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 -C /opt/
          rm gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2

      - name: Patch SoftDevice headers
        run: |
          mkdir -p /opt/nRF5_SDK_17.1.0_ddde560/components/softdevice/s340/headers/
          cp -r pca10056/s340/include/* /opt/nRF5_SDK_17.1.0_ddde560/components/softdevice/s340/headers/

      - name: Inject ANT license key
        run: |
          sed -i 's|#define ANT_LICENSE_KEY .*|#define ANT_LICENSE_KEY "${{ secrets.ANT_LICENSE_KEY }}"|' \
            /opt/nRF5_SDK_17.1.0_ddde560/components/softdevice/s340/headers/nrf_sdm.h

      - name: Build bootloader
        run: |
          cd bootloader/bootloader_s340/armgcc
          make -j4 RELEASE=1 BOARD=${{ matrix.board }}

      - name: Build application for ${{ matrix.board }}
        run: |
          cd pca10056/s340/armgcc
          make -j4 RELEASE=1 OPT=-O3 VERSION="${{ steps.version.outputs.version }}" CI=1 BOARD=${{ matrix.board }}

      - name: Write DFU private key to disk
        run: |
          echo "${{ secrets.DFU_PRIVATE_KEY }}" > private_key.pem

      - name: Generate DFU settings for ${{ matrix.board }}
        run: |
          cd pca10056/s340/armgcc
          nrfutil settings generate --family NRF52840 \
            --application _build_${{ matrix.board }}/nrf52840_xxaa_${{ matrix.board }}.hex \
            --application-version ${{ github.run_number }} \
            --bootloader-version 1 \
            --bl-settings-version 2 \
            --app-boot-validation VALIDATE_GENERATED_CRC \
            dfu_settings_${{ matrix.board }}.hex

      - name: Merge firmware hex for ${{ matrix.board }}
        run: |
          cd pca10056/s340/armgcc
          mergehex --merge \
            _build_${{ matrix.board }}/nrf52840_xxaa_${{ matrix.board }}.hex \
            dfu_settings_${{ matrix.board }}.hex \
            --output merged_firmware_${{ matrix.board }}.hex

      - name: Create DFU package for ${{ matrix.board }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          nrfutil pkg generate --hw-version 52 \
            --application pca10056/s340/armgcc/_build_${{ matrix.board }}/nrf52840_xxaa_${{ matrix.board }}.hex \
            --application-version ${{ github.run_number }} \
            --sd-req 0xCE \
            --key-file private_key.pem \
            bikeble_dfu-${{ matrix.board }}-${VERSION}.zip

      - name: Upload artifacts for ${{ matrix.board }}
        uses: actions/upload-artifact@v4
        with:
          name: bikeble-${{ matrix.board }}-firmware
          path: |
            bikeble_dfu-${{ matrix.board }}-${{ steps.version.outputs.version }}.zip
          retention-days: 7

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bikeble_dfu-${{ matrix.board }}-${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
